# Generated by Django 2.2.7 on 2019-11-21 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('anger', models.FloatField(blank=True)),
                ('contempt', models.FloatField(blank=True)),
                ('disgust', models.FloatField(blank=True)),
                ('fear', models.FloatField(blank=True)),
                ('happiness', models.FloatField(blank=True)),
                ('neutral', models.FloatField(blank=True)),
                ('sadness', models.FloatField(blank=True)),
                ('surprise', models.FloatField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
